spring:
  application:
    name: userService

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-user
    username: postgres
    password: harsh

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  server:
    port: 8081