server:
  port: 8081

spring:
  application:
    name: user-service  # ✅ use lowercase and hyphens (standard naming)

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-user
    username: postgres
    password: harsh
    driver-class-name: org.postgresql.Driver  # ✅ optional but good to include

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
